In [128]:
import pandas as pd
import numpy as np
import matplotlib as mp

In [129]:
#second stage - data loading 
#after the dabase is store we need to load her to be able to read it
filename = "Database/diabetes.csv"

df = pd.read_csv(filename)

In [130]:
df

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
0,1000,203.0,82,56.0,3.6,4.310000,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,NaN,NaN,29.0,38.0,720.0
1,1001,165.0,97,24.0,6.9,4.440000,Buckingham,29,female,64.0,218.0,large,112.0,68.0,NaN,NaN,46.0,48.0,360.0
2,1002,228.0,92,37.0,6.2,4.640000,Buckingham,58,female,61.0,256.0,large,190.0,92.0,185.0,92.0,49.0,57.0,180.0
3,1003,78.0,93,12.0,6.5,4.630000,Buckingham,67,male,67.0,119.0,large,110.0,50.0,NaN,NaN,33.0,38.0,480.0
4,1005,249.0,90,28.0,8.9,7.720000,Buckingham,64,male,68.0,183.0,medium,138.0,80.0,NaN,NaN,44.0,41.0,300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,41506,296.0,369,46.0,6.4,16.110001,Louisa,53,male,69.0,173.0,medium,138.0,94.0,130.0,94.0,35.0,39.0,210.0
399,41507,284.0,89,54.0,5.3,4.390000,Louisa,51,female,63.0,154.0,medium,140.0,100.0,146.0,102.0,32.0,43.0,180.0
400,41510,194.0,269,38.0,5.1,13.630000,Louisa,29,female,69.0,167.0,small,120.0,70.0,NaN,NaN,33.0,40.0,20.0
401,41752,199.0,76,52.0,3.8,4.490000,Louisa,41,female,63.0,197.0,medium,120.0,78.0,NaN,NaN,41.0,48.0,255.0
402,41756,159.0,88,79.0,2.0,NaN,Louisa,68,female,64.0,220.0,medium,100.0,72.0,NaN,NaN,49.0,58.0,900.0

In [131]:
#let's preview the first and last data 
df.head(2)

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
0,1000,203.0,82,56.0,3.6,4.31,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,NaN,NaN,29.0,38.0,720.0
1,1001,165.0,97,24.0,6.9,4.44,Buckingham,29,female,64.0,218.0,large,112.0,68.0,NaN,NaN,46.0,48.0,360.0

In [132]:
df.tail(2)

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
401,41752,199.0,76,52.0,3.8,4.49,Louisa,41,female,63.0,197.0,medium,120.0,78.0,NaN,NaN,41.0,48.0,255.0
402,41756,159.0,88,79.0,2.0,NaN,Louisa,68,female,64.0,220.0,medium,100.0,72.0,NaN,NaN,49.0,58.0,900.0

In [133]:
#after a short analysis the variables that we are going to study are 
#chol, stab.glu, glyhb, age, gender and weight
#the weight will be translate to kg

In [134]:
#let's clean the understand a bit more and clean this mess

In [135]:
df.shape

(403, 19)

In [136]:
#the current dataframe has 403 rows and 19 columns

In [137]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 403 entries, 0 to 402
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        403 non-null    int64
 1   chol      402 non-null    float64
 2   stab.glu  403 non-null    int64
 3   hdl       402 non-null    float64
 4   ratio     402 non-null    float64
 5   glyhb     390 non-null    float64
 6   location  403 non-null    object
 7   age       403 non-null    int64
 8   gender    403 non-null    object
 9   height    398 non-null    float64
 10  weight    402 non-null    float64
 11  frame     391 non-null    object
 12  bp.1s     398 non-null    float64
 13  bp.1d     398 non-null    float64
 14  bp.2s     141 non-null    float64
 15  bp.2d     141 non-null    float64
 16  waist     401 non-null    float64
 17  hip       401 non-null    float64
 18  time.ppn  400 non-null    float64
dtypes: float64(13), int64(3), object(3)
memory usage: 59.9+ KB

In [138]:
#in the variables that we are explaring the following have null entries - chol, glyhd and weight
#we will in the future remove those id of the consideration

In [139]:
df.describe()

,id,chol,stab.glu,hdl,ratio,glyhb,age,height,weight,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
count,403.000000,402.000000,403.000000,402.000000,402.000000,390.000000,403.000000,398.000000,402.000000,398.000000,398.000000,141.000000,141.000000,401.000000,401.000000,400.000000
mean,15978.310174,207.845771,106.672457,50.445274,4.521642,5.589769,46.851117,66.020101,177.592040,136.904523,83.321608,152.382979,92.524823,37.900249,43.039900,341.250000
std,11881.122124,44.445557,53.076655,17.262626,1.727886,2.242595,16.312333,3.918515,40.340666,22.741033,13.589227,21.712952,11.555198,5.729313,5.656713,309.540953
min,1000.000000,78.000000,48.000000,12.000000,1.500000,2.680000,19.000000,52.000000,99.000000,90.000000,48.000000,110.000000,60.000000,26.000000,30.000000,5.000000
25%,4792.500000,179.000000,81.000000,38.000000,3.200000,4.380000,34.000000,63.000000,151.000000,121.250000,75.000000,138.000000,84.000000,33.000000,39.000000,90.000000
50%,15766.000000,204.000000,89.000000,46.000000,4.200000,4.840000,45.000000,66.000000,172.500000,136.000000,82.000000,149.000000,92.000000,37.000000,42.000000,240.000000
75%,20336.000000,230.000000,106.000000,59.000000,5.400000,5.600000,60.000000,69.000000,200.000000,146.750000,90.000000,161.000000,100.000000,41.000000,46.000000,517.500000
max,41756.000000,443.000000,385.000000,120.000000,19.299999,16.110001,92.000000,76.000000,325.000000,250.000000,124.000000,238.000000,124.000000,56.000000,64.000000,1560.000000

In [140]:
df.isnull().sum()

id            0
chol          1
stab.glu      0
hdl           1
ratio         1
glyhb        13
location      0
age           0
gender        0
height        5
weight        1
frame        12
bp.1s         5
bp.1d         5
bp.2s       262
bp.2d       262
waist         2
hip           2
time.ppn      3
dtype: int64

In [141]:
#we can see that are 1 null in chol, 13 in glyhd and 1 in weight

In [142]:
(df == 0).sum()

id          0
chol        0
stab.glu    0
hdl         0
ratio       0
glyhb       0
location    0
age         0
gender      0
height      0
weight      0
frame       0
bp.1s       0
bp.1d       0
bp.2s       0
bp.2d       0
waist       0
hip         0
time.ppn    0
dtype: int64

In [143]:
#this step is for me on of the most important to understand if their are people in the same category

In [144]:
df['chol'].value_counts()

chol
179.0    11
204.0     9
203.0     7
194.0     7
219.0     7
         ..
342.0     1
200.0     1
266.0     1
222.0     1
284.0     1
Name: count, Length: 154, dtype: int64

In [145]:
df['stab.glu'].value_counts()

stab.glu
85     18
84     15
81     15
92     14
88     12
       ..
248     1
133     1
52      1
371     1
269     1
Name: count, Length: 116, dtype: int64

In [146]:
df['glyhb'].value_counts()

glyhb
4.67    6
4.40    6
4.31    5
4.41    5
5.35    5
       ..
9.18    1
5.46    1
6.34    1
5.37    1
4.49    1
Name: count, Length: 239, dtype: int64

In [147]:
df['age'].value_counts()

age
40    16
43    13
41    13
36    13
38    11
      ..
81     1
24     1
92     1
83     1
89     1
Name: count, Length: 68, dtype: int64

In [148]:
df['gender'].value_counts()

gender
female    234
male      169
Name: count, dtype: int64

In [149]:
df['weight'].value_counts()

weight
170.0    14
145.0    11
179.0    10
183.0    10
165.0    10
         ..
325.0     1
217.0     1
274.0     1
135.0     1
224.0     1
Name: count, Length: 140, dtype: int64

In [150]:
#we have a lot of subjects with the same values

In [151]:
#it will be important in the future

In [152]:
"""In the current state we can see that there are a lot of variables
the most important for the project were choosen -  id, chol, stb.glu, glyhb, age, gender and weight.
During the last steps we were able to check that there are a lot of id - people - with null entries, they will have to be remoed in the future.
Also, has a final thought, we can see that there are a lot of people with the same values and can be categorized"""

'In the current state we can see that there are a lot of variables\nthe most important for the project were choosen -  id, chol, stb.glu, glyhb, age, gender and weight.\nDuring the last steps we were able to check that there are a lot of id - people - with null entries, they will have to be remoed in the future.\nAlso, has a final thought, we can see that there are a lot of people with the same values and can be categorized'

In [154]:
#let's add a column saying if they have or not diabetes, >= 6,5 has diabetes\n<6,5 doesn't have
df['diabetes'] = (df['glyhb'] >= 6.5).astype(int)

In [155]:
df

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn,diabetes
0,1000,203.0,82,56.0,3.6,4.310000,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,NaN,NaN,29.0,38.0,720.0,0
1,1001,165.0,97,24.0,6.9,4.440000,Buckingham,29,female,64.0,218.0,large,112.0,68.0,NaN,NaN,46.0,48.0,360.0,0
2,1002,228.0,92,37.0,6.2,4.640000,Buckingham,58,female,61.0,256.0,large,190.0,92.0,185.0,92.0,49.0,57.0,180.0,0
3,1003,78.0,93,12.0,6.5,4.630000,Buckingham,67,male,67.0,119.0,large,110.0,50.0,NaN,NaN,33.0,38.0,480.0,0
4,1005,249.0,90,28.0,8.9,7.720000,Buckingham,64,male,68.0,183.0,medium,138.0,80.0,NaN,NaN,44.0,41.0,300.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,41506,296.0,369,46.0,6.4,16.110001,Louisa,53,male,69.0,173.0,medium,138.0,94.0,130.0,94.0,35.0,39.0,210.0,1
399,41507,284.0,89,54.0,5.3,4.390000,Louisa,51,female,63.0,154.0,medium,140.0,100.0,146.0,102.0,32.0,43.0,180.0,0
400,41510,194.0,269,38.0,5.1,13.630000,Louisa,29,female,69.0,167.0,small,120.0,70.0,NaN,NaN,33.0,40.0,20.0,1
401,41752,199.0,76,52.0,3.8,4.490000,Louisa,41,female,63.0,197.0,medium,120.0,78.0,NaN,NaN,41.0,48.0,255.0,0
402,41756,159.0,88,79.0,2.0,NaN,Louisa,68,female,64.0,220.0,medium,100.0,72.0,NaN,NaN,49.0,58.0,900.0,0

In [153]:
#let's keep only the columns that we need

In [156]:
new_df = df.loc[:, ['id', 'chol', 'stab.glu', 'glyhb', 'age', 'gender', 'weight', 'diabetes']]

In [157]:
new_df

        id   chol  stab.glu      glyhb  age  gender  weight  diabetes
0     1000  203.0        82   4.310000   46  female   121.0         0
1     1001  165.0        97   4.440000   29  female   218.0         0
2     1002  228.0        92   4.640000   58  female   256.0         0
3     1003   78.0        93   4.630000   67    male   119.0         0
4     1005  249.0        90   7.720000   64    male   183.0         1
..     ...    ...       ...        ...  ...     ...     ...       ...
398  41506  296.0       369  16.110001   53    male   173.0         1
399  41507  284.0        89   4.390000   51  female   154.0         0
400  41510  194.0       269  13.630000   29  female   167.0         1
401  41752  199.0        76   4.490000   41  female   197.0         0
402  41756  159.0        88        NaN   68  female   220.0         0

[403 rows x 8 columns]

In [158]:
#now let's remove the users with nulls

In [159]:
new_df = new_df.dropna()

In [160]:
new_df

        id   chol  stab.glu      glyhb  age  gender  weight  diabetes
0     1000  203.0        82   4.310000   46  female   121.0         0
1     1001  165.0        97   4.440000   29  female   218.0         0
2     1002  228.0        92   4.640000   58  female   256.0         0
3     1003   78.0        93   4.630000   67    male   119.0         0
4     1005  249.0        90   7.720000   64    male   183.0         1
..     ...    ...       ...        ...  ...     ...     ...       ...
397  41503  301.0        90   4.280000   89  female   115.0         0
398  41506  296.0       369  16.110001   53    male   173.0         1
399  41507  284.0        89   4.390000   51  female   154.0         0
400  41510  194.0       269  13.630000   29  female   167.0         1
401  41752  199.0        76   4.490000   41  female   197.0         0

[388 rows x 8 columns]

In [161]:
#let's check the date types

In [162]:
new_df.dtypes

id            int64
chol        float64
stab.glu      int64
glyhb       float64
age           int64
gender       object
weight      float64
diabetes      int64
dtype: object

In [163]:
"""Let's start the fun part - EDA"""

"Let's start the fun part - EDA\nFirst things first - >= 6,5 has diabetes\n<6,5 doesn't have\n"